# Generated by prisma-to-python - https://github.com/jmsv/prisma-to-python#readme
# Do not edit this file directly!

from enum import Enum
from typing import TypedDict, Optional
from datetime import datetime

# Enums

class FruitName(Enum):
    APPLE = "apple"
    BANANA = "banana"
    ORANGE = "orange"

# Types

class Fruit(TypedDict):
    fruit: FruitName
    price: int
    description: Optional[str]
    dateSold: datetime
    received: bool

# Models

class FruitOrders(TypedDict):
    _id: str
    fruit: list[Fruit]
